# Generated by Django 6.0.6 on 2026-07-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterModelTable(
            name='film',
            table=None,
        ),
    ]
