# Generated by Django 6.0.6 on 2026-07-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_actor_director_film_genres_film_actors_film_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
