# Generated by Django 6.0.6 on 2026-07-22 11:06

import django.core.validators
import films.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, upload_to='posters/', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.PositiveIntegerField(validators=[films.validators.validate_film_year], verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='Оценка от 1 до 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
