# Generated by Django 6.0.6 on 2026-08-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_alter_film_poster_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'permissions': [('publish_review', 'Может публиковать рецензии без модерации'), ('moderate_review', 'Может модерировать чужие рецензии')], 'verbose_name': 'Рецензия', 'verbose_name_plural': 'Рецензии'},
        ),
    ]
