# Generated by Django 6.0.6 on 2026-08-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['-year'], 'permissions': [('can_feature_film', 'Может выделять фильм в подборку')], 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
    ]
